return function(globalSystem, position)
    return globalSystem:newEntity()
        :addComponent('Walking')
        :addComponent('Position', {position = position})
        :addComponent('Rotation', {rotation = 0})
        --:addComponent('UserControlled')
        :addComponent('Velocity', {velocity = Vector(0,0)})
        --:addComponent('Drawable', {type = 'rect'})
        --:addComponent('DrawRectangle', { size = {x = 8, y = 14} })
        :addComponent('Body', { parts = {} })
end